// <auto-generated />
namespace Mite.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTariffsCharacter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTariffsCharacter));
        
        string IMigrationMetadata.Id
        {
            get { return "201808021009247_AddTariffsCharacter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
